server.port: 8080
management.port: 8099
hidEdgePro:
  username: admin
  password: S3cret?
  devices:
    test:
      description: Test Unit
      url: http://192.168.1.111
aws:
  region: us-east-1
  sqs:
    state:
      push: hiddoorstate
    control:
      push: hidcmdresponse
      pull: hidcmdrequest

