management.port: 8080
hidEdgePro:
  url: https://10.19.4.130
  username: admin
  password: Password1
  devices:
    coop:
      description: Coop Door
      url: http://10.19.4.130
    external:
      description: External Door
      url: http://10.19.4.129
      # username: user
      # password: otherPassw0rd
application:
  cloud:
    sync:
      server: 12.34.56.78
      apiKey: ASDFGHJKLQWERTYUIOPZXCVBNM1234567890

