spring:
  groovy.template.check-template-location: false
server:
  context-path: ''
  port: 8080
management:
  port: 8181
api:
  keys:
    ALL: enabled
aws:
  region: us-east-1
  sqs:
    pushQueue: mncc-commands
    pullQueue: mncc-state
    healthQueue: mncc-health
logging:
  level:
    com.mnclimbingcoop: DEBUG
