spring:
  groovy.template.check-template-location: false
server:
  context-path: ''
  port: 6590

management:
  port: 6591
api:
  keys:
    ALL: enabled
hidEdgePro:
  username: admin
# password: S3cret?
# devices:
#   coop:
#     description: Main Entrance
#     url: http://192.169.0.1
#   loadingbay:
#     description: Loading Bay Door
#     url: http://192.169.0.2
schedule:
  survey:
    rate: 21600000 # 6 hours in MS.
    initialDelay: 20000 # 20 seconds
  door:
    rate: 10000 # 10 seconds in MS.
    initialDelay: 3000 # 3 seconds
  health:
    rate: 20000 # 20 seconds in MS.
    initialDelay: 30000 # 30 seconds
aws:
  region: us-east-1
# sqs:
#   pushQueue:   mncc-state
#   pullQueue:   mncc-commands
#   healthQueue: mncc-health
logging:
  file: /var/log/night-watchman/night-watchman.log
  path: /var/log/night-watchman
  level:
    com.mnclimbingcoop.service: DEBUG
