spring:
  groovy.template.check-template-location: false
server:
  context-path: ''
  port: 6590
management:
  port: 6591
api:
  keys:
    ALL: enabled
hidEdgePro:
  username: admin
  password: Z3@RLr2LE8
  devices:
    evo:
      description: Evo Controller
      url: http://192.168.1.116
schedule:
  survey:
    rate: 21600000 # 6 hours in MS.
    initialDelay: 20000 # 20 seconds
  door:
    rate: 10000 # 10 seconds in MS.
    initialDelay: 3000 # 3 seconds
  events:
    rate: 2000 # 2 seconds in MS.
    initialDelay: 10000 # 5 seconds
  commands:
    rate: 5000 # 5 seconds in MS.
    initialDelay: 7000 # 7 seconds
aws:
  region: us-east-1
  sqs:
    pushQueue: mncc-state
    pullQueue: mncc-commands
logging:
  level:
    com.mnclimbingcoop.service: DEBUG
