spring:
  groovy.template.check-template-location: false
server:
  context-path: ''
  port: 8080
management:
  port: 8099
hidEdgePro:
  username: admin
  password: S3cret?
  devices:
    coop:
      description: Main Entrance
      url: http://10.19.4.130
    loadingbay:
      description: Loading Bay Door
      url: http://10.19.4.129
aws:
  region: us-east-1
  sqs:
    queue: mncc-state

